# try-catch-throw实现异常处理

## 基本说明
1. try-catch-throw机制只有在C++中才有，在C语言中没有
2. catch可以有多个，但至少要有一个
3. throw可以有1个，可以有多个，也可以没有？？？


## 异常处理流程
1. 处理可以是给出错误提示信息，然后让程序换到另一条路上继续执行下去
也可以是不得不提前结束程序，但在结束之前做一些必要工作，如将内存中的数据写入文件、关闭打开的文件、释放动态分配的内存空间等
2. 函数A在执行过程中发现异常时可以不加处理，而只是拋出一个异常给A的调用者，即函数B
拋出异常而不加处理会导致函数A立即中止，在这种情况下，函数B可以选择捕获A拋出的异常进行处理，也可以选择置之不理
如果置之不理，这个异常就会被拋给B的调用者，以此类推
如果一层层的函数都不处理异常，异常最终会被拋给最外层的main函数
main函数应该处理异常，如果main函数也不处理异常，那么程序就会立即异常地中止


## 基本格式
```
try
{
    可能出现异常的语句组
    throw 表达式;
}
catch(异常类型1)
{
    异常处理代码
}
catch(异常类型2)
{
    异常处理代码
}
....
```


## 执行过程
1. 如果try块执行过程中没有异常抛出，那就跳过所有的catch块继续往下执行
2. 如果try块继续过程中抛出了异常，则立即跳转到异常类型匹配的catch块中，执行完成后跳转到所有catch块后面继续往下执行
3. 如果try块继续过程中抛出了异常，但没有任何catch块能够匹配，程序会立刻停止运行，并返回以下信息：
```
terminate called after throwing an instance of 'int'
```


## throw


## catch类型
1. catch(...)
匹配所有的异常类型
注意：有多个catch块时，catch(...)只能放到后面，作为最后一个catch块，否则会报错


## 只写try-catch，不写throw


## 问题
1. 看到代码里只写了try-catch(...)，没有throw，类似于python中try-except的用法？？？
2. ...是什么异常类型？？？
3. 异常的类型只有double，没有float？？？
